"""Tests for the provenance header on generated OpenMC input files."""

from __future__ import annotations

import xml.etree.ElementTree as ET

import pytest
from promptmc import __version__
from promptmc.openmc_integration import OpenMCRunner
from promptmc.provenance import (
    current_command,
    provenance_header,
    write_xml_with_provenance,
)
from promptmc.templates import get_template


def test_header_records_version_timestamp_command():
    header = provenance_header("promptmc template criticality -o settings.xml")
    assert "Generated by PromptMC" in header
    assert f"Version:   {__version__}" in header
    # ISO-8601 UTC timestamp, e.g. 2026-06-19T22:36:09Z
    assert "Timestamp: " in header
    assert "Z" in header
    assert "promptmc template criticality -o settings.xml" in header


def test_header_is_a_well_formed_xml_comment():
    header = provenance_header("promptmc template criticality -o out.xml")
    assert header.startswith("<!--")
    assert header.endswith("-->")
    # Embedding the header in a document must parse cleanly.
    doc = f"<root>{header}<a/></root>"
    ET.fromstring(doc)  # nosec B314 - test fixture, trusted input


def test_double_hyphen_in_command_is_sanitized():
    """Long options (``--output``) must not break XML comment parsing."""
    header = provenance_header(
        "promptmc template criticality --output settings.xml --particles 10000"
    )
    # The raw double-hyphen token is illegal inside an XML comment.
    assert "--" not in header.replace("<!--", "").replace("-->", "")
    doc = f"<settings>{header}</settings>"
    root = ET.fromstring(doc)  # nosec B314 - test fixture, trusted input
    assert root.tag == "settings"


def test_current_command_normalizes_program_name(monkeypatch):
    monkeypatch.setattr(
        "sys.argv",
        ["/some/venv/bin/promptmc", "template", "criticality"],
    )
    assert current_command() == "promptmc template criticality"


def test_current_command_falls_back_when_driven_via_api(monkeypatch):
    """When invoked through pytest/python, argv[0] is rewritten to promptmc."""
    monkeypatch.setattr("sys.argv", ["pytest", "-k", "something"])
    assert current_command().startswith("promptmc ")


def test_write_xml_with_provenance_round_trips(tmp_path):
    root = ET.Element("settings")
    ET.SubElement(root, "batches").text = "10"
    out = tmp_path / "settings.xml"

    write_xml_with_provenance(root, out, command="promptmc demo --flag x")

    content = out.read_text()
    assert content.startswith("<?xml")
    assert "Generated by PromptMC" in content
    # Re-parsing keeps the document usable; the comment is ignored.
    parsed = ET.parse(out).getroot()
    assert parsed.find("batches").text == "10"


def test_template_render_includes_provenance(tmp_path, monkeypatch):
    monkeypatch.setattr(
        "sys.argv",
        ["promptmc", "template", "criticality", "--output", "settings.xml"],
    )
    out = tmp_path / "settings.xml"
    get_template("criticality").render(output_path=out, particles=12345)

    content = out.read_text()
    assert "Generated by PromptMC" in content
    assert "Command:" in content
    # The model OpenMC actually reads is unchanged and re-parses.
    root = ET.parse(out).getroot()
    assert root.find("particles").text == "12345"


def test_generate_configuration_includes_provenance(tmp_path):
    out = tmp_path / "settings.xml"
    OpenMCRunner().generate_configuration(output_path=out, particles=999)

    content = out.read_text()
    assert "Generated by PromptMC" in content
    root = ET.parse(out).getroot()
    assert root.find("particles").text == "999"


@pytest.mark.parametrize("template_type", ["criticality", "shielding"])
def test_every_template_is_provenanced(tmp_path, template_type):
    out = tmp_path / f"{template_type}.xml"
    get_template(template_type).render(output_path=out)
    assert "Generated by PromptMC" in out.read_text()
