"""Provenance headers for PromptMC-generated OpenMC input files.

Every ``settings.xml`` PromptMC emits carries a leading XML comment recording
the PromptMC version, the generation timestamp, and the exact command that
produced it. The header makes a generated file self-describing and
reproducible without changing what OpenMC reads (comments are ignored by the
parser).
"""

from __future__ import annotations

import shlex
import sys
import xml.etree.ElementTree as ET  # nosec B405
from datetime import datetime, timezone
from pathlib import Path

from promptmc._typing import PathLike

# XML declaration written verbatim ahead of the provenance comment. Matches the
# style ElementTree's ``xml_declaration=True`` emits so generated files stay
# byte-for-byte consistent with the rest of the codebase.
XML_DECLARATION = "<?xml version='1.0' encoding='utf-8'?>"


def current_command() -> str:
    """Reconstruct the command line that invoked PromptMC.

    The entry-point path in ``sys.argv[0]`` is normalized to the bare
    ``promptmc`` program name so the recorded command is portable and
    copy-pasteable rather than tied to one machine's virtualenv layout.

    Returns:
        The best-effort command string, e.g.
        ``promptmc template criticality --output settings.xml``.
    """
    argv = sys.argv
    if not argv or not argv[0]:
        return "promptmc"
    prog = Path(argv[0]).name
    # When PromptMC is driven through its Python API rather than the CLI,
    # argv[0] is the host program (pytest, python, a notebook kernel, ...).
    # Fall back to the package name so the header still names the tool.
    if prog in {"promptmc", "promptmc-mcp"}:
        return shlex.join([prog, *argv[1:]])
    return shlex.join(["promptmc", *argv[1:]])


def _escape_comment(text: str) -> str:
    """Make ``text`` safe to embed inside an XML comment.

    XML forbids the ``--`` token inside comments, which a reconstructed
    command line routinely contains (``--output``, ``--particles``); a stray
    pair makes the whole file fail to parse. Split every run of hyphens so no
    double-hyphen survives, and pad a trailing hyphen (also illegal right
    before ``-->``). The command stays readable and the file stays well-formed.

    Args:
        text: Raw comment body.

    Returns:
        A comment-safe version of ``text``.
    """
    while "--" in text:
        text = text.replace("--", "- -")
    if text.endswith("-"):
        text += " "
    return text


def provenance_header(command: str | None = None) -> str:
    """Build the leading XML comment recording how a file was generated.

    Args:
        command: The command to record. Defaults to the current invocation
            via :func:`current_command`.

    Returns:
        A well-formed XML comment block (no trailing newline).
    """
    # Imported lazily: this module is pulled in low in the import graph
    # (via openmc_integration during ``promptmc`` package init), before the
    # package-level ``__version__`` attribute is assigned.
    from promptmc import __version__

    cmd = command if command is not None else current_command()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "Generated by PromptMC. Do not edit by hand; regenerate instead.",
        f"Version:   {__version__}",
        f"Timestamp: {timestamp}",
        f"Command:   {cmd}",
    ]
    body = "\n".join(f"  {line}" for line in lines)
    return f"<!--\n{_escape_comment(body)}\n-->"


def write_xml_with_provenance(
    root: ET.Element,
    output_path: PathLike,
    command: str | None = None,
) -> Path:
    """Serialize an XML tree to ``output_path`` with a provenance header.

    The element tree is indented in place (matching the previous
    ``tree.write`` behavior) and written as: XML declaration, provenance
    comment, then the document body.

    Args:
        root: Root element of the document to write.
        output_path: Destination path; parent directories are created.
        command: Command to record in the header; defaults to the current
            invocation.

    Returns:
        The path written.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    body = ET.tostring(root, encoding="unicode")
    header = provenance_header(command)

    output_path.write_text(
        f"{XML_DECLARATION}\n{header}\n{body}\n",
        encoding="utf-8",
    )
    return output_path
